version: '2.1'
services:
    fluentbit-instance:
    image: fluent/fluent-bit:1.0
    ports:
      - "24223:24223"
    volumes:
      - "./info_bit:/custom_conf"
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/custom_conf/in_fluentbit.conf"]
  fluentd_instance:
    build:
      context: ./info_cont
      dockerfile: ./Dockerfile
    image: custom-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./info_cont:/custom-config"
    command: ["-c", "/custom-config/in_docker.conf"]
  elasticseacrh-instance:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  application-instance:
      image: alpine
      depends_on:
        - fluentbit-instance
      command: ["echo", "Hello World"]
      logging:
        driver: fluentd
        options:
          tag: "docker.{{.ID}}"
          fluentd-address: fluentbit-instance
#  application-instance:
#      build: ./log_generating_container
#      image: log_generating_container
#      depends_on:
#        - fluentd_instance
